### ISSUE TITLE
Change spellings of licence to license for consistency

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#38]
https://github.com/restrictcontentpro/rcp-site-child/blob/c626b0ddc7b44ce5bd5edd69af03ac431f75210a/includes/edd-functions.php#L151

https://github.com/restrictcontentpro/rcp-site-child/blob/c626b0ddc7b44ce5bd5edd69af03ac431f75210a/includes/edd-functions.php#L178

**Comment by sumobi** [comment]
Ugh, shame on me

**Comment by michaelbeil** [comment]
Tisk tisk. Those New Zealanders, I tell ya ... :smile:
