### ISSUE TITLE
Improve the pricing table feature list

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#39]
In the pro/ultimate columns, we don't show that the free add-ons are included. Seems obvious to us, but it would be good to include that to make it clear.

Also, it would be good to mention that any new pro add-ons we release are included in the pro/ultimate for active license holders.

**Comment by sumobi** [comment]
Going to go with something like this:

![screen shot 2016-04-19 at 5 34 02 am](https://cloud.githubusercontent.com/assets/52581/14613399/67abe934-05f0-11e6-9d79-e964bd738821.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
Also going to update the modal window (when you click on the "3 pro add-ons" link so it includes a line about getting any additional add-ons:

![screen shot 2016-04-19 at 5 41 50 am](https://cloud.githubusercontent.com/assets/52581/14613651/8d3ac912-05f1-11e6-8622-85aaf0fac5cc.png)

**Comment by sumobi** [comment]
Changed the text to say "+ any we release in the future!"

![screen shot 2016-04-19 at 5 44 23 am](https://cloud.githubusercontent.com/assets/52581/14613720/d2c3a576-05f1-11e6-9170-05eacf5874f9.png)

**Comment by mindctrl** [comment]
Looks good!

**Comment by pippinsplugins** [comment]
Love it

**Comment by sumobi** [comment]
Done diddy done
