### ISSUE TITLE
The calling of the author box

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/rcp-site-child#41]
Our author boxes are requesting some sprucing up:
![slack-imgs-2](https://cloud.githubusercontent.com/assets/4752949/15056071/7d5dccf6-12d5-11e6-9d97-2091edb15b34.png)
![slack-imgs-1](https://cloud.githubusercontent.com/assets/4752949/15056095/959feb6e-12d5-11e6-90de-6d4001d9f42b.png)

When I had a talk with author box, he said that he wants to look more like EDD's author box:
![slack-imgs](https://cloud.githubusercontent.com/assets/4752949/15056113/b3f5b3e6-12d5-11e6-8ec1-72565d5189ea.png)

**Comment by sumobi** [comment]
Will get to this soon. Need to style the main parent theme's author boxes better.

**Comment by sumobi** [comment]
Closing, the author box was improved some time ago
