### ISSUE TITLE
Create featured images for new official free add-ons

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#42]
We recently added two new add-ons that need featured images: EDD FES Vendor Limits and EDD Wallet.

**Comment by sumobi** [comment]
👍

**Comment by sumobi** [comment]
![screen shot 2016-06-01 at 7 06 35 pm](https://cloud.githubusercontent.com/assets/52581/15701065/05c0e2de-282c-11e6-84b4-34f9f3b66760.png)

**Comment by pippinsplugins** [comment]
Looking good!

**Comment by mindctrl** [comment]
@sumobi thank you sir!
