### ISSUE TITLE
Add add-ons feed

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/rcp-site-child#44]
We need an add-ons feed just like AffiliateWP so that we can finish https://github.com/restrictcontentpro/restrict-content-pro/issues/484

**Comment by pippinsplugins** [comment]
Code to register feed here: https://github.com/restrictcontentpro/rcp-site-child/pull/43

Now just need the feed template and CSS.

**Comment by sumobi** [comment]
This was done
