### ISSUE TITLE
Add icon for WooCommerce integration 

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/rcp-site-child#45]
### Mobile: 

![slack-imgs](https://cloud.githubusercontent.com/assets/4752949/15790607/c691923a-2997-11e6-86d6-a6af42e113c2.png)

### Desktop:
![screen shot on 2016-06-03 at 14-31-11](https://cloud.githubusercontent.com/assets/4752949/15790704/657b0318-2998-11e6-838e-167faa40b182.png)

**Comment by sumobi** [comment]
![screen shot 2016-06-05 at 4 35 24 pm](https://cloud.githubusercontent.com/assets/52581/15803620/9c4373b8-2b3b-11e6-8296-66d19adbf42d.png)

**Comment by michaelbeil** [comment]
👌🏻
