### ISSUE TITLE
XML sitemap is broken

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#47]
https://restrictcontentpro.com/sitemap_index.xml

`ERROR: This is not a valid feed template.`

**Comment by sumobi** [comment]
This is being caused by the `rcp_cf_feed_rewrite()` function in our custom functionality plugin. Tracking down the issue...

**Comment by sumobi** [comment]
@cklosowski Can you give me a hand on this one? AffiliateWP and RCP both show an error when clicking the `XML Sitemap` button inside Yoast SEO:

![screen shot 2016-07-07 at 6 22 46 pm](https://cloud.githubusercontent.com/assets/52581/16644279/ea4bc37e-446f-11e6-8047-da00f1a6fa2d.png)


![screen shot 2016-07-07 at 6 22 52 pm](https://cloud.githubusercontent.com/assets/52581/16644275/e3c73f1a-446f-11e6-8fcf-14db5b55e8a6.png)


EDD loads fine:

![screen shot 2016-07-07 at 6 21 15 pm](https://cloud.githubusercontent.com/assets/52581/16644264/c34e47ec-446f-11e6-897d-1440d1e2a5cf.png)

I took the RSS code from EDD for AffiliateWP and RCP originally, but when I compare the code I can't see anything different.

If I comment out this exact line in the RCP functionality plugin (AffWP has one too), clear the permalinks, and then click the Yoast SEO button I get the correct result:

https://github.com/restrictcontentpro/rcp-functionality/blob/master/rcp-functionality.php#L74

EDD's function is identical, it's included in the EDD theme here:
https://github.com/easydigitaldownloads/EDD-Site/blob/master/includes/feed-rss.php#L42

**Comment by cklosowski** [comment]
We have a custom rewrite rule on EDD in nginx so it never hits this WordPress rewrite rule. Currently the other sites aren't configured to accept user redirects in Nginx, contacting pagely to get that resolved. Here's the rules for when we're ready.

```
rewrite ^/sitemap_index\.xml$ /index.php?sitemap=1 last;
rewrite ^/([^/]+?)-sitemap([0-9]+)?\.xml$ /index.php?sitemap=$1&sitemap_n=$2 last;
```

**Comment by sumobi** [comment]
Thanks @cklosowski !

**Comment by mindctrl** [comment]
This works now with our server upgrades.

**Comment by sumobi** [comment]
Sweet
