### ISSUE TITLE
URLs in comments cause issues on mobile

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#48]
URLs in comments don't wrap early enough, and end up breaking the mobile view, causing the whole page to get squeezed.

![img_0861](https://cloud.githubusercontent.com/assets/1254870/16604898/2acc578e-42f8-11e6-9e00-d6cd25e73d3d.PNG)

---

![img_0868](https://cloud.githubusercontent.com/assets/1254870/16604929/56b8f4ec-42f8-11e6-8242-15ef3d9553dc.PNG)

**Comment by michaelbeil** [comment]
Noticed this the other day as well.

**Comment by sumobi** [comment]
Fixed via https://github.com/restrictcontentpro/rcp-site-child/commit/e9f2f6cca91997d655be1aa3aead1676a87d140c
