### ISSUE TITLE
Clear changelog transient when saving RCP core download

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#49]
The changelog is cached for 24 hours [here](https://github.com/restrictcontentpro/rcp-site-child/blob/c8f2893f3497330bf7ee6f9a7e693f7b8029ec39/includes/theme-tweaks.php#L329). We pushed 2.6 and 2.6.1 within 24 hours of each other, but we're still not seeing the 2.6 stuff.

I propose we clear that transient on the `save_post_download` hook when the ID matches RCP core... ID 479.

**Comment by sumobi** [comment]
This was implemented

**Comment by mindctrl** [comment]
This is no longer working.

**Comment by sumobi** [comment]
Hmm perhaps it was never working to start with then

**Comment by sumobi** [comment]
Weirdly, this works fine with `delete_transient`, just not `delete_site_transient`

**Comment by sumobi** [comment]
Unless anyone convinces me otherwise I'm keeping it as delete_transient and considering this resolved.
