### ISSUE TITLE
Improve display of docs search results on support page

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#53]
The results need some padding and a little jazz.

![image](https://cloud.githubusercontent.com/assets/1254870/19397468/fceab9ec-9215-11e6-9979-c7b5e85dc8a6.png)

I like how the EDD site displays them:

![image](https://cloud.githubusercontent.com/assets/1254870/19397482/08fbf016-9216-11e6-9b77-322da91b3be5.png)

**Comment by sumobi** [comment]
👍  Will get this tidied up

**Comment by sumobi** [comment]
done

![screen shot 2016-10-16 at 8 20 58 pm](https://cloud.githubusercontent.com/assets/52581/19415957/176f2090-93de-11e6-9d9a-03726b8df2e9.png)

**Comment by pippinsplugins** [comment]
Looks great!
