### ISSUE TITLE
Improve link visibility

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#55]
Right now it's hard to see links, they don't stand out enough from regular text.

![image](https://cloud.githubusercontent.com/assets/1254870/19939214/66d344cc-a0fe-11e6-9832-e4bacb7d501b.png)

^ they're more visible in the screenshot, due to loss of quality I guess, than they are on the site itself.

**Comment by sumobi** [comment]
👍 Good point. They used to underlines but I messed with the parent theme and stripped everything back. Let's put them back on the child theme, or at least make links blue or purple.

**Comment by michaelbeil** [comment]
I noticed a link issue in the notification area as well: 
![screen shot on 2016-11-17 at 15-42-55](https://cloud.githubusercontent.com/assets/4752949/20393570/a608d92e-acdc-11e6-9ada-1b658abf8a06.png)

**Comment by sumobi** [comment]
Made links blue so they are easier to see.

The banner was designed to have the anchor link wrapped around all the text so everything is clickable. For the maintenance banner it looks like that one bit of text was linked, hence why it looks like there's no styling. If we do more maintenance I'll revisit this but I prefer the banner how it is.
