### ISSUE TITLE
Notification area font is a bit large

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/rcp-site-child#57]
Proposed fix:
![slack-imgs](https://cloud.githubusercontent.com/assets/4752949/20394719/d8de869c-ace0-11e6-966a-d51a20a8e344.gif)

**Comment by sumobi** [comment]
Will revisit in the future. That maintenance notice was far too long - it looks fine for cyber monday/black friday. I prefer how it stands out currently with the bolded text.
