### ISSUE TITLE
Possible display issue with Safari

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#59]
Customer reported having issues on our add-on pages in Safari. Screenshot:

![image](https://cloud.githubusercontent.com/assets/1254870/21537050/8dbbce1a-cd59-11e6-913b-3f1af760eb30.png)

I was unable to replicate it on two computers. I don't have any version details from the customer.

@sumobi do things look good for you too?

**Comment by pippinsplugins** [comment]
Works just fine for me.

**Comment by sumobi** [comment]
Missed this, never seen that issue and always test with Safari. Closing but let me know if there are any other reports! Could have been a weird caching issue.
