### ISSUE TITLE
Outdated refund policy

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#62]
The refund policy link in the footer is outdated. The latest one is here: http://docs.restrictcontentpro.com/article/1706-refund-policy

Instead of loading the refund policy in a modal and having to keep 2 copies updated, I propose we link directly to the above policy on the doc site.

**Comment by sumobi** [comment]
Fixed the modal window, the links were pointing to an outdated refund policy page in the admin, the one at checkout however was correct. The page has been deleted.

@mindctrl I don't agree with linking to the doc for a few reasons:

1. I believe a refund policy should always exist on the same site/domain that sells the actual product.
2. There are multiple links that point to the refund policy, in the footer, 2 on the pricing page, and 1 at checkout. If we link them to the doc site (even in a new window) there's a chance we could lose the sale altogether.
4. It's nice in support to simply just link a customer directly to the refund policy on our site and then have them go on to learn more about the product: https://restrictcontentpro.com/purchase-terms-refund-policy/

I see no harm in having both.
