### ISSUE TITLE
Add authorize.net to front page

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/rcp-site-child#63]
We need to add Authorize.net here:
<img width="1431" alt="screen shot 2017-03-29 at 1 08 46 pm" src="https://cloud.githubusercontent.com/assets/1034109/24469392/eb9c645e-1480-11e7-9472-92cc81727c32.png">

**Comment by pippinsplugins** [comment]
Also need to add it to this:

```
Built-in Integrations

Accept credit cards with Stripe, Braintree, 2Checkout, or PayPal Website Payments Pro. Restrict Content Pro also supports PayPal Standard and Express, as well as multiple payment options at the same time.
```

**Comment by sumobi** [comment]
👍

**Comment by sumobi** [comment]
Closing via https://github.com/restrictcontentpro/rcp-site-child/commit/a928056dbbcb01a215f69d859bbfec6a76472113
