### ISSUE TITLE
Login confusion on checkout page

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#66]
Our checkout page doesn't have a login link, and if someone comes to the site that already has a subscription and they try to purchase again while logged out, they get an error about having to log in first. Easy to do if it's been a year or more, or if someone else in an organization bought from the same email.

A customer was confused by this, saying: 

> I can't buy a subscription because it prompts me to login to an account first. I can't create an account because there is no function on your site to create an account. How do I get you guys my money?

Since the menu doesn't show on the checkout, the customer doesn't have the chance to find the log in link. Not having the menu on checkout is great, but I think we should have some way on the checkout page to log in when someone already has an account, unless we figure out a way to automatically deal with this issue in EDD, Recurring, or whatever.

For comparison, EDD site has a login link on the checkout that shows inline when the link is clicked.

Another idea is if someone is logged out and enters an email that's already is use (determined via ajax request), automatically showing the login form with a small login notice would be a nice smooth experience I think.

**Comment by pippinsplugins** [comment]
@amdrew could you try to look at this soon?

**Comment by amdrew** [comment]
Will do

**Comment by amdrew** [comment]
@mindctrl @pippinsplugins 

Borrowed some code from the EDD theme which does this:

<img width="759" alt="screenshot 2017-11-15 18 24 21" src="https://user-images.githubusercontent.com/52581/32820248-4056dc24-ca32-11e7-9959-cff1e676e0f9.png">

___

How does this look (local atm):

<img width="867" alt="screenshot 2017-11-15 18 21 30" src="https://user-images.githubusercontent.com/52581/32820173-e5ded328-ca31-11e7-9737-47d8e7062035.png">

___

When you click the link it replaces it with the login form:

<img width="885" alt="screenshot 2017-11-15 18 21 37" src="https://user-images.githubusercontent.com/52581/32820183-ed918778-ca31-11e7-880e-afbe52385352.png">

___

If we like it, I think I'll add to the AffiliateWP site also.

**Comment by nosegraze** [comment]
I think it's cool. 👍

**Comment by mindctrl** [comment]
Looks good!

**Comment by amdrew** [comment]
Sweet, will chuck it up soon

**Comment by amdrew** [comment]
It's live
