### ISSUE TITLE
Ensure Perfect Audience tracking only runs on production site

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-site-child#72]
We've seen some issues with weird conversion numbers, and the going theory is it's from someone's local dev environment.

We should add some kind of check [here](https://github.com/restrictcontentpro/rcp-site-child/blob/8465a037fe2305134a65a50f43fd17e02e33b4f6/includes/scripts.php#L41) to ensure it only runs on the production site.

One idea is to simply do a constant defined check that we set in the production site's wp-config.php.

**Comment by mindctrl** [comment]
PR: https://github.com/restrictcontentpro/rcp-site-child/pull/73

**Comment by mindctrl** [comment]
I don't see anything in the functionality plugin that needs to be updated. https://github.com/restrictcontentpro/rcp-functionality

**Comment by pippinsplugins** [comment]
Merged, deploy!
